
package tse.java.soappdi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.4
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmpresaServicePortService", targetNamespace = "/pdi", wsdlLocation = "https://pdi-mbravo95-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/pdi/ws/empresas.wsdl")
public class EmpresaServicePortService
    extends Service
{

    private final static URL EMPRESASERVICEPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPRESASERVICEPORTSERVICE_EXCEPTION;
    private final static QName EMPRESASERVICEPORTSERVICE_QNAME = new QName("/pdi", "EmpresaServicePortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://pdi-mbravo95-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com/pdi/ws/empresas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPRESASERVICEPORTSERVICE_WSDL_LOCATION = url;
        EMPRESASERVICEPORTSERVICE_EXCEPTION = e;
    }

    public EmpresaServicePortService() {
        super(__getWsdlLocation(), EMPRESASERVICEPORTSERVICE_QNAME);
    }

    public EmpresaServicePortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPRESASERVICEPORTSERVICE_QNAME, features);
    }

    public EmpresaServicePortService(URL wsdlLocation) {
        super(wsdlLocation, EMPRESASERVICEPORTSERVICE_QNAME);
    }

    public EmpresaServicePortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPRESASERVICEPORTSERVICE_QNAME, features);
    }

    public EmpresaServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpresaServicePortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmpresaServicePort
     */
    @WebEndpoint(name = "EmpresaServicePortSoap11")
    public EmpresaServicePort getEmpresaServicePortSoap11() {
        return super.getPort(new QName("/pdi", "EmpresaServicePortSoap11"), EmpresaServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpresaServicePort
     */
    @WebEndpoint(name = "EmpresaServicePortSoap11")
    public EmpresaServicePort getEmpresaServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("/pdi", "EmpresaServicePortSoap11"), EmpresaServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPRESASERVICEPORTSERVICE_EXCEPTION!= null) {
            throw EMPRESASERVICEPORTSERVICE_EXCEPTION;
        }
        return EMPRESASERVICEPORTSERVICE_WSDL_LOCATION;
    }

}
