
package pdi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PdiPortService", targetNamespace = "/pdi", wsdlLocation = "file:/home/rita/IdeaProjects/CargaUY/ProveedorEmpresas/src/main/resources/empresas.wsdl")
public class PdiPortService
    extends Service
{

    private final static URL PDIPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PDIPORTSERVICE_EXCEPTION;
    private final static QName PDIPORTSERVICE_QNAME = new QName("/pdi", "PdiPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/rita/IdeaProjects/CargaUY/ProveedorEmpresas/src/main/resources/empresas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PDIPORTSERVICE_WSDL_LOCATION = url;
        PDIPORTSERVICE_EXCEPTION = e;
    }

    public PdiPortService() {
        super(__getWsdlLocation(), PDIPORTSERVICE_QNAME);
    }

    public PdiPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PDIPORTSERVICE_QNAME, features);
    }

    public PdiPortService(URL wsdlLocation) {
        super(wsdlLocation, PDIPORTSERVICE_QNAME);
    }

    public PdiPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PDIPORTSERVICE_QNAME, features);
    }

    public PdiPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PdiPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PdiPort
     */
    @WebEndpoint(name = "PdiPortSoap11")
    public PdiPort getPdiPortSoap11() {
        return super.getPort(new QName("/pdi", "PdiPortSoap11"), PdiPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PdiPort
     */
    @WebEndpoint(name = "PdiPortSoap11")
    public PdiPort getPdiPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("/pdi", "PdiPortSoap11"), PdiPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PDIPORTSERVICE_EXCEPTION!= null) {
            throw PDIPORTSERVICE_EXCEPTION;
        }
        return PDIPORTSERVICE_WSDL_LOCATION;
    }

}
