
package empresa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "EmpresaPortService", targetNamespace = "/empresa", wsdlLocation = "file:/home/rita/IdeaProjects/CargaUY/ProveedorEmpresas/src/main/resources/empresas.wsdl")
public class EmpresaPortService
    extends Service
{

    private final static URL EMPRESAPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPRESAPORTSERVICE_EXCEPTION;
    private final static QName EMPRESAPORTSERVICE_QNAME = new QName("/empresa", "EmpresaPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/rita/IdeaProjects/CargaUY/ProveedorEmpresas/src/main/resources/empresas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPRESAPORTSERVICE_WSDL_LOCATION = url;
        EMPRESAPORTSERVICE_EXCEPTION = e;
    }

    public EmpresaPortService() {
        super(__getWsdlLocation(), EMPRESAPORTSERVICE_QNAME);
    }

    public EmpresaPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPRESAPORTSERVICE_QNAME, features);
    }

    public EmpresaPortService(URL wsdlLocation) {
        super(wsdlLocation, EMPRESAPORTSERVICE_QNAME);
    }

    public EmpresaPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPRESAPORTSERVICE_QNAME, features);
    }

    public EmpresaPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmpresaPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmpresaPort
     */
    @WebEndpoint(name = "EmpresaPortSoap11")
    public EmpresaPort getEmpresaPortSoap11() {
        return super.getPort(new QName("/empresa", "EmpresaPortSoap11"), EmpresaPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpresaPort
     */
    @WebEndpoint(name = "EmpresaPortSoap11")
    public EmpresaPort getEmpresaPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("/empresa", "EmpresaPortSoap11"), EmpresaPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPRESAPORTSERVICE_EXCEPTION!= null) {
            throw EMPRESAPORTSERVICE_EXCEPTION;
        }
        return EMPRESAPORTSERVICE_WSDL_LOCATION;
    }

}
